# Database Credentials and Information
db_name: "neo4j"
uri: "bolt://localhost:7687"
user: "neo4j"
password: "12345678"

# Dataset information
dataset_name: "BPIC19"
semantic_header_path: "json_files/BPIC19.json"
dataset_description_path: "json_files/BPIC19_DS.json"
use_sample: false

# Import settings
verbose: false
batch_size: 25000
use_preprocessed_files: false
